/**
 * Conversation History Manager
 *
 * Manages conversation history for iterative feature refinement.
 * Maintains context across refinement iterations so Claude understands
 * what the user is refining.
 *
 * This is session-based storage that resets when the modal closes.
 */

/**
 * Represents a feature breakdown generated by AI.
 * Contains the structured output of analyzing a feature description.
 */
export interface FeatureBreakdown {
  title: string;
  description: string;
  tasks: FeatureTask[];
  estimatedComplexity?: 'low' | 'medium' | 'high';
  dependencies?: string[];
  assumptions?: string[];
}

export interface FeatureTask {
  title: string;
  description: string;
  acceptanceCriteria?: string[];
  priority?: 'low' | 'medium' | 'high';
}

/**
 * Represents a single message in the conversation history.
 * Compatible with Claude API message format.
 */
export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

/**
 * Claude API message format for sending conversation history.
 */
export interface ClaudeApiMessage {
  role: 'user' | 'assistant';
  content: string;
}

/**
 * Manages conversation history for feature refinement sessions.
 */
class ConversationHistoryManager {
  private history: ConversationMessage[] = [];

  /**
   * Initialize a new conversation with an initial feature description.
   * Clears any existing history and starts fresh.
   *
   * @param initialDescription - The initial feature description from the user
   */
  initialize(initialDescription: string): void {
    this.history = [];
    this.addUserFeedback(initialDescription);
  }

  /**
   * Add user feedback/refinement request to the conversation history.
   *
   * @param feedback - The user's refinement request or feedback
   */
  addUserFeedback(feedback: string): void {
    this.history.push({
      role: 'user',
      content: feedback,
      timestamp: new Date(),
    });
  }

  /**
   * Add AI's generated breakdown response to the conversation history.
   * Converts the structured FeatureBreakdown to a string representation
   * for the conversation context.
   *
   * @param breakdown - The AI's generated feature breakdown
   */
  addAIResponse(breakdown: FeatureBreakdown): void {
    const content = this.formatBreakdownAsContent(breakdown);
    this.history.push({
      role: 'assistant',
      content,
      timestamp: new Date(),
    });
  }

  /**
   * Get the full conversation history.
   *
   * @returns Array of all conversation messages
   */
  getHistory(): ConversationMessage[] {
    return [...this.history];
  }

  /**
   * Get conversation history formatted for Claude API.
   * Strips timestamps and returns only role/content pairs.
   *
   * @returns Array of messages in Claude API format
   */
  getHistoryForClaudeApi(): ClaudeApiMessage[] {
    return this.history.map(({ role, content }) => ({
      role,
      content,
    }));
  }

  /**
   * Clear all conversation history.
   * Call this when the modal closes or when starting a completely new feature.
   */
  reset(): void {
    this.history = [];
  }

  /**
   * Get the number of messages in the conversation.
   *
   * @returns The count of messages
   */
  getMessageCount(): number {
    return this.history.length;
  }

  /**
   * Check if there is any conversation history.
   *
   * @returns True if there are messages in history
   */
  hasHistory(): boolean {
    return this.history.length > 0;
  }

  /**
   * Get the last message in the conversation.
   *
   * @returns The last message or undefined if history is empty
   */
  getLastMessage(): ConversationMessage | undefined {
    return this.history.length > 0
      ? this.history[this.history.length - 1]
      : undefined;
  }

  /**
   * Format a FeatureBreakdown as a string for conversation context.
   * This helps Claude understand what was previously generated.
   */
  private formatBreakdownAsContent(breakdown: FeatureBreakdown): string {
    const parts: string[] = [];

    parts.push(`# ${breakdown.title}`);
    parts.push('');
    parts.push(breakdown.description);
    parts.push('');

    if (breakdown.tasks.length > 0) {
      parts.push('## Tasks');
      breakdown.tasks.forEach((task, index) => {
        parts.push(`${index + 1}. **${task.title}**`);
        parts.push(`   ${task.description}`);
        if (task.acceptanceCriteria && task.acceptanceCriteria.length > 0) {
          parts.push('   Acceptance Criteria:');
          task.acceptanceCriteria.forEach((criteria) => {
            parts.push(`   - ${criteria}`);
          });
        }
        if (task.priority) {
          parts.push(`   Priority: ${task.priority}`);
        }
      });
      parts.push('');
    }

    if (breakdown.estimatedComplexity) {
      parts.push(`**Estimated Complexity:** ${breakdown.estimatedComplexity}`);
    }

    if (breakdown.dependencies && breakdown.dependencies.length > 0) {
      parts.push('');
      parts.push('**Dependencies:**');
      breakdown.dependencies.forEach((dep) => {
        parts.push(`- ${dep}`);
      });
    }

    if (breakdown.assumptions && breakdown.assumptions.length > 0) {
      parts.push('');
      parts.push('**Assumptions:**');
      breakdown.assumptions.forEach((assumption) => {
        parts.push(`- ${assumption}`);
      });
    }

    return parts.join('\n');
  }
}

// Export a singleton instance for session-based usage
export const conversationHistoryManager = new ConversationHistoryManager();

// Also export the class for cases where multiple instances are needed
export { ConversationHistoryManager };
